version: '3.9'
services:
  api:
    build: ./backend
    container_name: api
    command: dev
    working_dir: /app
    volumes:
      - ./backend/src:/app/src
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3001:3001
    env_file:
      - .env
    tty: true
    stdin_open: true
  db:
    container_name: database
    image: mysql:8.0.32
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"] # Deve aguardar o banco ficar operacional
      timeout: 10s
      retries: 5